### ISSUE TITLE
how do you get this to work

### ISSUE THREAD

**Issue by Pickymarker** [joshua-hallwd/clonehero-bot#1]
how do you get this to work

**Comment by joshua-hallwd** [comment]
> how do you get this to work

Currently, download the repo as a zip file. Install all of the requirements with pip and then depending on OS you would run the main app.py file. The program runs or pauses when the letter 'T' is pressed on the keyboard. The program will exit when the letter 'Y' is pressed on the keyboard. I will add this to the readme.
